name: pr-filed

on:
  pull_request:
    types: [opened, edited]
    branches:
      - flatcar-master
      - flatcar-master-alpha
      - flatcar-master-beta

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const path = require('path')
            const scriptPath = path.resolve('./.github/workflows/pr-filed.ts')
            require(scriptPath)({context, github})
