# TODO: trigger it on pull request being pushed to again
name: pr-filed

on:
  pull_request:
    types: [opened, edited]
    branches:
      - flatcar-master
      - flatcar-master-alpha
      - flatcar-master-beta

jobs:
  parse-pr-body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: KrnowakTestAppOrg/patch-tracking
          token: ${{secrets.BOTS_PAT}}
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.BOTS_PAT}}
          script: |
            const path = require('path')
            const scriptPath = path.resolve('./pr-filed.js')
            require(scriptPath)({context, github})
